version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=m00dl3LuzV@ll3!
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=LuzValleDB
    volumes:
      - './mariadb_data:/var/lib/mysql'
  moodle:
    image: bitnami/moodle:4.2
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=m00dl3LuzV@ll3!
      - MOODLE_DATABASE_NAME=LuzValleDB
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminLuzValle
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
